drop DATABASE EduSys
GO
USE EduSys
-- NHÂN VIÊN
CREATE TABLE NHANVIEN 
(
	MANHANVIEN VARCHAR(20) NOT NULL,
	MATKHAU VARCHAR(20) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	VAITRO BIT DEFAULT 0,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANHANVIEN)
)
GO 
-- CHUYÊN ĐỀ
CREATE TABLE CHUYENDE 
(
	MACD CHAR(5) NOT NULL,
	TENCD NVARCHAR(50) NOT NULL,
	HOCPHI FLOAT NOT NULL,
	THOILUONG INT NOT NULL,
	NGAYTAO DATE DEFAULT GETDATE(),
	HINH NVARCHAR(50) NOT NULL,
	MOTA NVARCHAR(255) NOT NULL,
	CONSTRAINT PK_CHUYENDE PRIMARY KEY (MACD)
)
GO
-- KHÓA HỌC
CREATE TABLE KHOAHOC
(
	MAKH INT IDENTITY (1,1) NOT NULL,
	MACD CHAR(5) NOT NULL,
	HOCPHI FLOAT NOT NULL,
	THOILUONG INT NOT NULL,
	NGAYKG DATE NOT NULL,
	NGAYTAO DATE DEFAULT GETDATE(),
	GHICHU  NVARCHAR(255) NULL,
	NGUOITAO VARCHAR(20) NOT NULL,
	CONSTRAINT PK_KHOAHOC PRIMARY KEY (MAKH),
	CONSTRAINT FK_KHOAHOC_CHUYENDE FOREIGN KEY (MACD) REFERENCES CHUYENDE(MACD) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FK_KHOAHOC_NHANVIEN FOREIGN KEY (NGUOITAO) REFERENCES NHANVIEN(MANHANVIEN) ON DELETE NO ACTION ON UPDATE CASCADE
)
GO
-- NGƯỜI HỌC : 
CREATE TABLE NGUOIHOC
(
	MANH CHAR(7) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	GIOITINH BIT DEFAULT 1,
	NGAYSINH DATE NOT NULL,
	DIENTHOAI VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	GHICHU NVARCHAR(255) NULL,
	NGUOITAO VARCHAR(20) NOT NULL,
	NGAYDK DATE DEFAULT GETDATE(),
	CONSTRAINT PK_NGUOIHOC PRIMARY KEY (MANH),
	CONSTRAINT FK_NGUOIHOC_NHANVIEN FOREIGN KEY (NGUOITAO) REFERENCES NHANVIEN(MANHANVIEN) ON DELETE NO ACTION ON UPDATE CASCADE
)
GO 
CREATE TABLE HOCVIEN 
(
	MAHV INT IDENTITY (1,1) NOT NULL,
	MAKH INT NOT NULL,
	MANH CHAR(7) NOT NULL,
	DIEM FLOAT DEFAULT 0,
	--TRANGTHAI BIT NULL,
	CONSTRAINT PK_HOCVIEN PRIMARY KEY (MAHV),
	CONSTRAINT FK_HOCVIEN_NGUOIHOC FOREIGN KEY (MANH) REFERENCES NGUOIHOC(MANH) ,-- ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FK_HOCVIEN_KHOAHOC FOREIGN KEY (MAKH) REFERENCES KHOAHOC(MAKH)--ON DELETE CASCADE ON UPDATE CASCADE 
)

ALTER TABLE HOCVIEN
ALTER COLUMN  DIEM DEFAULT 0;


-- Thay đổi ràng buộc trong bảng HOCVIEN để sử dụng ON DELETE NO ACTION
--ALTER TABLE HOCVIEN
--DROP CONSTRAINT FK_HOCVIEN_KHOAHOC; -- Xóa ràng buộc cũ

--ALTER TABLE HOCVIEN
--ADD CONSTRAINT FK_HOCVIEN_KHOAHOC FOREIGN KEY (MAKH) REFERENCES KHOAHOC(MAKH) ON DELETE NO ACTION ON UPDATE CASCADE;


SELECT * FROM NHANVIEN
SELECT * FROM CHUYENDE
SELECT * FROM KHOAHOC
SELECT * FROM NGUOIHOC
SELECT * FROM HOCVIEN
SELECT * FROM KHOAHOC
--INSERT INTO HOCVIEN  ( MAKH ,MANH ) VALUES ( 29,'PH98767' )

--DROP TABLE NHANVIEN
--DROP TABLE CHUYENDE
--DROP TABLE KHOAHOC
--DROP TABLE NGUOIHOC
--DROP TABLE HOCVIEN

-- + NHAN VIEN
INSERT INTO NHANVIEN (MANHANVIEN , MATKHAU , HOTEN , VAITRO) VALUES ('NV3' ,1 , N'Nguyễn Quốc Toàn' , 0) 
-- UPDATE NHANVIEN SET MATKHAU = ? , HOTEN = ? , VAITRO = ? WHERE MANHANVIEN = ? 
-- DELETE FROM NHANVIEN WHERE MANHANVIEN = ?
-- SELECT MANHANVIEN , MATKHAU , HOTEN , VAITRO FROM NHANVIEN
-- SELECT MANHANVIEN , MATKHAU , HOTEN , VAITRO FROM NHANVIEN WHERE MANHANVIEN LIKE 'NV'


-- + CHUYEN DE 
-- INSERT INTO CHUYENDE (MACD , TENCD , HOCPHI , THOILUONG , HINH , MOTA) VALUES ( ? , ? , ? , ? , ? , ?)
-- UPDATE CHUYENDE SET TENCD = ? , HOCPHI = ?, THOILUONG = ?, NGAYTAO  =? , HINH = ?, MOTA = ? WHERE MACD = ?
-- DELETE FROM CHUYENDE WHERE MACD = 's'
-- SELECT MACD , TENCD , HOCPHI ,THOILUONG , NGAYTAO , HINH , MOTA FROM CHUYENDE
-- SELECT MACD , TENCD , HOCPHI ,THOILUONG , NGAYTAO , HINH , MOTA FROM CHUYENDE WHERE MACD = ''

-- + KHOA HOC
-- INSERT INTO KHOAHOC (MACD , HOCPHI , THOILUONG ,  NGAYKG  , GHICHU ,  NGUOITAO) VALUES (? , ?, ? ,? , ?  , ?)
-- UPDATE KHOAHOC SET HOCPHI = ? ,  THOILUONG = ? , NGAYKG = ? , GHICHU = ? WHERE MAKH = ?
-- SELECT MAKH , MACD , HOCPHI , THOILUONG , NGAYTAO , NGAYKG , GHICHU , NGUOITAO FROM KHOAHOC
-- SELECT MAKH , MACD , HOCPHI , THOILUONG , NGAYTAO , NGAYKG , GHICHU , NGUOITAO FROM KHOAHOC WHERE MACD = ?

-- + NGUOI HOHOC
-- INSERT INTO NGUOIHOC (MANH , HOTEN , GIOITINH , NGAYSINH , DIENTHOAI , EMAIL , GHICHU , NGUOITAO ) VALUES (? ,? ,? ,? ,? ,? ,? , ?)
-- INSERT INTO NGUOIHOC (MANH , HOTEN , GIOITINH , NGAYSINH , DIENTHOAI , EMAIL , GHICHU , NGUOITAO ) VALUES ('PH37150' ,N'Nguyễn Tiến Mạnh' ,1 ,'07-26-2003' ,'0868819924' ,'manh@gmail.com' ,N'Mạnh Ghi chu' , 'NV4')
-- UPDATE NGUOIHOC SET HOTEN  = ?, GIOITINH = ? , NGAYSINH  = ?, DIENTHOAI = ? , EMAIL = ? , GHICHU = ? ,  NGAYDK = ? WHERE MANH =?
--DELETE FROM NGUOIHOC WHERE MANH = ?
-- SELECT MANH , HOTEN , GIOITINH , NGAYSINH , DIENTHOAI , EMAIL , GHICHU , NGUOITAO , NGAYDK FROM NGUOIHOC
-- SELECT MANH , HOTEN , GIOITINH , NGAYSINH , DIENTHOAI , EMAIL , GHICHU , NGUOITAO , NGAYDK FROM NGUOIHOC WHERE MANH == ?
 SELECT  MANH , HOTEN , GIOITINH , NGAYSINH , DIENTHOAI , EMAIL , GHICHU , NGUOITAO , NGAYDK FROM NGUOIHOC WHERE MANH like '%N%' or HOTEN like '%N%'
-- + HOCVIEN 
-- INSERT INTO HOCVIEN  ( MAKH ,MANH ) VALUES ( ?,? )
-- UPDATE HOCVIEN SET DIEM = ? WHERE MAHV = ?
-- SELECT MAHV , MAKH , MANH , DIEM FROM HOCVIEN
-- SELECT MAHV , MAKH , MANH , DIEM FROM HOCVIEN WHERE MAHV = ?
  DELETE FROM HOCVIEN WHERE MAHV = ?


SELECT MAHV , MAKH , MANH , DIEM FROM HOCVIEN WHERE MAKH = 1
select * from HOCVIEN
SELECT MAHV , MAKH ,  NGUOIHOC.MANH , HOTEN , DIEM FROM HOCVIEN
JOIN NGUOIHOC ON HOCVIEN.MANH = NGUOIHOC.MANH


-- update CHUYENDE set HINH = 'anhThuMuc.jpg'


SELECT * FROM NHANVIEN
SELECT * FROM CHUYENDE
select * from KHOAHOC

--INSERT INTO KHOAHOC (MACD , HOCPHI , THOILUONG ,  NGAYKG  , NGAYTAO ,  NGUOITAO) VALUES ('CD001' , 10000, 50 ,'12-12-2024 ', '08-26-2023'  , 'NV4')
select * from NGUOIHOC
SELECT * FROM HOCVIEN
--INSERT INTO HOCVIEN  ( MAKH ,MANH , DIEM) VALUES ( 3,'PH37150', 10 )
 
---UPDATE NGUOIHOC SET   NGAYDK = '2023-09-14' WHERE MANH = 'PH37150'

select MANHANVIEN , MATKHAU , HOTEN , VAITRO from NHANVIEN where MANHANVIEN = ? and MATKHAU = ? 

select MANHANVIEN , MATKHAU , HOTEN , VAITRO from NHANVIEN

--UPDATE NHANVIEN Set MATKHAU = ? WHERE MANHANVIEN = ? 

SELECT MANHANVIEN , MANHANVIEN , HOTEN , VAITRO FROM NHANVIEN WHERE MANHANVIEN = ? 

--insert into NHANVIEN values ('NV1', '1', N'Nguyễn Tiến Mạnh' ,1)

select * from NHANVIEN

SELECT * FROM HOCVIEN WHERE MAHV = ?

SELECT * FROM NHANVIEN
SELECT * FROM CHUYENDE
select * from KHOAHOC where YEAR(NGAYKG) = 2004


--INSERT INTO KHOAHOC (MACD , HOCPHI , THOILUONG ,  NGAYKG  , GHICHU ,  NGUOITAO) VALUES ('CD004' , 120000, 87 ,'2023-11-03' , N'JavaScript cơ ban '  , 'NV2')
--update KHOAHOC set THOILUONG = 87 where MACD = 'CD004' and MACD = 'CD002'

--DELETE FROM KHOAHOC WHERE MAKH = ?

---- UPDATE KHOAHOC SET NGAYKG = ? , GHICHU = ? WHERE MAKH = ?

--SELECT MANH , HOTEN , GIOITINH , NGAYSINH , DIENTHOAI , EMAIL , GHICHU , NGUOITAO , NGAYDK FROM NGUOIHOC WHERE MANH = 'PH123'

--SELECT MANH , HOTEN , NGAYSINH , GIOITINH , DIENTHOAI , EMAIL FROM NGUOIHOC
--WHERE  HOTEN LIKE ? AND MANH NOT IN (SELECT MANH FROM HOCVIEN WHERE MAKH = ? )

select * from NGUOIHOC
INSERT INTO NGUOIHOC (MANH , HOTEN , GIOITINH , NGAYSINH , DIENTHOAI , EMAIL , GHICHU , NGUOITAO , NGAYDK) VALUES ('PH56564' ,N'bbbb' ,1 ,'07-26-2003' ,'0868819924' ,'manh@gmail.com' ,N'Khải Ghi chu' , 'NV4' ,'01-22-2021')


SELECT DISTINCT YEAR(NGAYKG) AS NAM FROM KHOAHOC ORDER BY NAM DESC

update KHOAHOC set  NGAYTAO ='07-22-2019' , NGAYKG = '11-22-2019' 
where MAKH = 6

select * from KHOAHOC
